/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import ModelBeans.Hora;
import ModelConexao.ConexaoBD;
import java.sql.SQLException;
import java.text.DateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Aurelio Macie Junior
 */
public class MenuPrincipal extends javax.swing.JFrame {

    ConexaoBD conex = new ConexaoBD();
    CadastroDeUsuarios usuario = new CadastroDeUsuarios();
    ProntaEntrega entrega = new ProntaEntrega();
    Relatorio relatorio = new Relatorio();
    Financas financa = new Financas();
    CadastroDeClientes cliente = new CadastroDeClientes();
    CadastroDeFornecedor fornecedor = new CadastroDeFornecedor();
    CadastroDeFuncionarios funcionario = new CadastroDeFuncionarios();
    CadastroDeMaterial material = new CadastroDeMaterial();
    StockMaterial stock = new StockMaterial();
    Venda venda = new Venda();
    Info info = new Info();
    //Info info = new Info();
    /**
     * Creates new form MenuPrincipal1
     */
    public MenuPrincipal(String usuario) {
        initComponents();
        jLabelUsuario.setText(usuario);
        conex.conexao();
        timer1.start();
        
        //Serve Para Exibir A Data Actual Do Sistema.
        Date data = new Date();
        DateFormat formatadorD = DateFormat.getDateInstance(DateFormat.LONG);
        jLabelDataDoSistema.setText(formatadorD.format(data));
        
        //Agora A Hora Do Sistema    
        Hora mostra_hora = new Hora();
        mostra_hora.ler_hora();
        jLabelHoraDoSistema.setText("Hora " +mostra_hora.hora);

    }

    private MenuPrincipal() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        timer1 = new org.netbeans.examples.lib.timerbean.Timer();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelDataDoSistema = new javax.swing.JLabel();
        jLabelHoraDoSistema = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonCadastroUsuarios = new javax.swing.JButton();
        jButtonCadastroFuncionarios = new javax.swing.JButton();
        jButtonCadastroClientes = new javax.swing.JButton();
        jButtonFornecedores = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButtonCadastroMaterial = new javax.swing.JButton();
        jButtonAdicionar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButtonVenda = new javax.swing.JButton();
        jButtonAgendamento = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenuDeInformacaoDoSistema = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        timer1.addTimerListener(new org.netbeans.examples.lib.timerbean.TimerListener() {
            public void onTime(java.awt.event.ActionEvent evt) {
                timer1OnTime(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 51, 255));

        jPanel3.setBackground(new java.awt.Color(51, 0, 51));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemProjecto/windows8_125px.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Menu Principal");

        jLabelDataDoSistema.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelDataDoSistema.setForeground(new java.awt.Color(255, 255, 255));

        jLabelHoraDoSistema.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelHoraDoSistema.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(548, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 340, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelHoraDoSistema, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDataDoSistema, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(536, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(0, 535, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabelHoraDoSistema, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelDataDoSistema, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cadastro De Pessoal E Cliente.:");

        jButtonCadastroUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemProjecto/IconParaMenuPrincipalUsuario_125px.png"))); // NOI18N
        jButtonCadastroUsuarios.setToolTipText("Usuário");
        jButtonCadastroUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroUsuariosActionPerformed(evt);
            }
        });

        jButtonCadastroFuncionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemProjecto/TrabalhadorColorido_male_125px.png"))); // NOI18N
        jButtonCadastroFuncionarios.setToolTipText("Operário");
        jButtonCadastroFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroFuncionariosActionPerformed(evt);
            }
        });

        jButtonCadastroClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemProjecto/Clienteman_120px.png"))); // NOI18N
        jButtonCadastroClientes.setToolTipText("Cliente");
        jButtonCadastroClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroClientesActionPerformed(evt);
            }
        });

        jButtonFornecedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemProjecto/truck1_120px.png"))); // NOI18N
        jButtonFornecedores.setToolTipText("Fornecedor");
        jButtonFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFornecedoresActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Registro De Material E Estoque.:");

        jButtonCadastroMaterial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemProjecto/REGISTRARMATERIAL_125px.png"))); // NOI18N
        jButtonCadastroMaterial.setToolTipText("Material");
        jButtonCadastroMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroMaterialActionPerformed(evt);
            }
        });

        jButtonAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemProjecto/addicaoDePRODUCTOOOO_125px_1.png"))); // NOI18N
        jButtonAdicionar.setToolTipText("Estoque");
        jButtonAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Bloco Operatório.:");

        jButtonVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemProjecto/SHOPPING_cart_125px.png"))); // NOI18N
        jButtonVenda.setToolTipText("Venda");
        jButtonVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVendaActionPerformed(evt);
            }
        });

        jButtonAgendamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemProjecto/LITERATUREBOOKAGENDAMENTO_120px.png"))); // NOI18N
        jButtonAgendamento.setToolTipText("Agendamento E Relatório De Venda");
        jButtonAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgendamentoActionPerformed(evt);
            }
        });

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemProjecto/PrntaEntregaresume_125px.png"))); // NOI18N
        jButton9.setToolTipText("Pronta Entrega");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemProjecto/Financas_duration_finance_125px.png"))); // NOI18N
        jButton10.setToolTipText("Finanças, Ganho");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(51, 0, 51));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Usuario.: ");

        jLabelUsuario.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabelUsuario.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(121, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButtonCadastroUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonCadastroClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonCadastroFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonFornecedores, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(99, 99, 99)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButtonCadastroMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(95, 95, 95)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButtonVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addComponent(jLabel4)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButtonAgendamento, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jButtonCadastroMaterial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonVenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonCadastroFuncionarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonCadastroUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonFornecedores, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCadastroClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAgendamento, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jMenu1.setText("Cadastros");
        jMenu1.setToolTipText("Cadastro De Pessoal E Cliente");

        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemProjecto/Mini_Usuario_businessman_10px.png"))); // NOI18N
        jMenuItem9.setText("Usuário");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem9);

        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemProjecto/Mini_worker_male_10px.png"))); // NOI18N
        jMenuItem10.setText("Operário");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem10);

        jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemProjecto/Mini_Clientemanager_10px.png"))); // NOI18N
        jMenuItem11.setText("Cliente");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem11);

        jMenuItem12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemProjecto/Mini_truck_10px.png"))); // NOI18N
        jMenuItem12.setText("Fornecedor");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem12);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Material");
        jMenu2.setToolTipText("Registro De Material E Estoque");

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemProjecto/Mini_Materialgear_10px.png"))); // NOI18N
        jMenuItem6.setText("Registro");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemProjecto/Mini_add_10px.png"))); // NOI18N
        jMenuItem8.setText("Estoque");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem8);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Operações");
        jMenu3.setToolTipText("Bloco Operatório");

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemProjecto/Mini_shopping_cart_10px.png"))); // NOI18N
        jMenuItem3.setText("Efectuar Venda");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemProjecto/Mini_duration_finance_10px.png"))); // NOI18N
        jMenuItem4.setText("Finanças");
        jMenu3.add(jMenuItem4);

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemProjecto/Mini_resume_10px.png"))); // NOI18N
        jMenuItem5.setText("Entrega De Material");
        jMenu3.add(jMenuItem5);

        jMenuBar1.add(jMenu3);

        jMenu5.setText("Relatório");
        jMenu5.setToolTipText("Relatório");

        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemProjecto/Mini_literature_10px.png"))); // NOI18N
        jMenuItem7.setText("Relatório De Venda");
        jMenu5.add(jMenuItem7);

        jMenuBar1.add(jMenu5);
        jMenuBar1.add(jMenu6);

        jMenu7.setText("Caixa");
        jMenu7.setToolTipText("Caixa");
        jMenuBar1.add(jMenu7);

        jMenuDeInformacaoDoSistema.setText("Acerca De");
        jMenuDeInformacaoDoSistema.setToolTipText("Informações");

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemProjecto/MenuInformation_10px.png"))); // NOI18N
        jMenuItem2.setText("Info");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenuDeInformacaoDoSistema.add(jMenuItem2);

        jMenuBar1.add(jMenuDeInformacaoDoSistema);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1238, 639));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadastroUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroUsuariosActionPerformed
        try {
            conex.executaSql("select * from usuario where nome='"+jLabelUsuario.getText()+"'");
            conex.rs.first();
                if(conex.rs.getString("tipo").equals("Administrador")){
                   if(usuario==null){
                       usuario = new CadastroDeUsuarios();
                       usuario.setVisible(true);
                       usuario.setResizable(false); 
                   }else{
                       usuario.setVisible(true);
                       usuario.setResizable(false);                         
                   }
                }else{
                   JOptionPane.showMessageDialog(rootPane, "Não Tem Permissão Para Acessar Essa Funcionalidade, Contacte O Administrador!","ERRO", JOptionPane.ERROR_MESSAGE); 
                }
        } catch (SQLException ex) {
                   JOptionPane.showMessageDialog(rootPane, "Não Tem Permissão Para Acessar Essa Funcionalidade, Contacte O Administrador!","ERRO", JOptionPane.ERROR_MESSAGE); 
        }
    }//GEN-LAST:event_jButtonCadastroUsuariosActionPerformed

    private void jButtonCadastroFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroFuncionariosActionPerformed
        try {
            conex.executaSql("select * from usuario where nome='"+jLabelUsuario.getText()+"'");
            conex.rs.first();
                if(conex.rs.getString("tipo").equals("Administrador")){
                   if(funcionario==null){
                       funcionario = new CadastroDeFuncionarios();
                       funcionario.setVisible(true);
                       funcionario.setResizable(false); 
                   }else{
                       funcionario.setVisible(true);
                       funcionario.setResizable(false);                         
                   }
                   //CadastroDeUsuarios c1 = new CadastroDeUsuarios();
                   //c1.setVisible(true);
                   //c1.setResizable(false);   
                }else{
                   JOptionPane.showMessageDialog(rootPane, "Não Tem Permissão Para Acessar Essa Funcionalidade, Contacte O Administrador!","ERRO", JOptionPane.ERROR_MESSAGE); 
                }
        } catch (SQLException ex) {
                   JOptionPane.showMessageDialog(rootPane, "Não Tem Permissão Para Acessar Essa Funcionalidade, Contacte O Administrador!","ERRO", JOptionPane.ERROR_MESSAGE); 
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCadastroFuncionariosActionPerformed

    private void jButtonCadastroClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroClientesActionPerformed
                   if(cliente==null){
                       cliente = new CadastroDeClientes();
                       cliente.setVisible(true);
                       cliente.setResizable(false); 
                   }else{
                       cliente.setVisible(true);
                       cliente.setResizable(false);                         
                   }

        //CadastroDeClientes c1 = new CadastroDeClientes();
        //c1.setVisible(true);
        //c1.setResizable(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCadastroClientesActionPerformed

    private void jButtonFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFornecedoresActionPerformed
        try {
            conex.executaSql("select * from usuario where nome='"+jLabelUsuario.getText()+"'");
            conex.rs.first();
                if(conex.rs.getString("tipo").equals("Administrador")){
                   if(fornecedor==null){
                       fornecedor = new CadastroDeFornecedor();
                       fornecedor.setVisible(true);
                       fornecedor.setResizable(false); 
                   }else {
                       fornecedor.setVisible(true);
                       fornecedor.setResizable(false);                         
                   }
                }else{
                   JOptionPane.showMessageDialog(rootPane, "Não Tem Permissão Para Acessar Essa Funcionalidade, Contacte O Administrador!","ERRO", JOptionPane.ERROR_MESSAGE); 
                }
        } catch (SQLException ex) {
                   JOptionPane.showMessageDialog(rootPane, "Não Tem Permissão Para Acessar Essa Funcionalidade, Contacte O Administrador!","ERRO", JOptionPane.ERROR_MESSAGE); 
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonFornecedoresActionPerformed

    private void jButtonVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVendaActionPerformed
     if(venda==null){
        venda= new Venda();
        venda.setVisible(true);
        venda.setResizable(false);
     }else{
        venda.setVisible(true);
        venda.setResizable(false);
     }        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonVendaActionPerformed

    private void jButtonAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgendamentoActionPerformed
        try {
            conex.executaSql("select * from usuario where nome='"+jLabelUsuario.getText()+"'");
            conex.rs.first();
                if(conex.rs.getString("tipo").equals("Administrador")){
                   if(relatorio==null){
                       relatorio = new Relatorio();
                       relatorio.setVisible(true);
                       relatorio.setResizable(false); 
                   }else{
                       relatorio.setVisible(true);
                       relatorio.setResizable(false);                         
                   }   
                }else{
                   JOptionPane.showMessageDialog(rootPane, "Não Tem Permissão Para Acessar Essa Funcionalidade, Contacte O Administrador!","ERRO", JOptionPane.ERROR_MESSAGE); 
                }
        } catch (SQLException ex) {
                   JOptionPane.showMessageDialog(rootPane, "Não Tem Permissão Para Acessar Essa Funcionalidade, Contacte O Administrador!","ERRO", JOptionPane.ERROR_MESSAGE); 
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAgendamentoActionPerformed

    private void jButtonAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarActionPerformed
        try {
            conex.executaSql("select * from usuario where nome='"+jLabelUsuario.getText()+"'");
            conex.rs.first();
                if(conex.rs.getString("tipo").equals("Administrador")){
                    if(material==null){
                       stock = new StockMaterial();
                       stock.setVisible(true);
                       stock.setResizable(false); 
                   }else{
                       stock.setVisible(true);
                       stock.setResizable(false);                         
                   }                    
                    //StockMaterial s = new StockMaterial();
                    //s.setVisible(true);
                    //s.setResizable(false);   
                }else{
                   JOptionPane.showMessageDialog(rootPane, "Não Tem Permissão Para Acessar Essa Funcionalidade, Contacte O Administrador!","ERRO", JOptionPane.ERROR_MESSAGE); 
                }
        } catch (SQLException ex) {
                   JOptionPane.showMessageDialog(rootPane, "Não Tem Permissão Para Acessar Essa Funcionalidade, Contacte O Administrador!","ERRO", JOptionPane.ERROR_MESSAGE); 
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAdicionarActionPerformed

    private void jButtonCadastroMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroMaterialActionPerformed
        try {
            conex.executaSql("select * from usuario where nome='"+jLabelUsuario.getText()+"'");
            conex.rs.first();
                if(conex.rs.getString("tipo").equals("Administrador")){
                    if(material==null){
                       material = new CadastroDeMaterial();
                       material.setVisible(true);
                       material.setResizable(false); 
                   }else{
                       material.setVisible(true);
                       material.setResizable(false);                         
                   }
                    //CadastroDeMaterial c1 = new CadastroDeMaterial();
                    //c1.setVisible(true);
                    //c1.setResizable(false);   
                }else{
                   JOptionPane.showMessageDialog(rootPane, "Não Tem Permissão Para Acessar Essa Funcionalidade, Contacte O Administrador!","ERRO", JOptionPane.ERROR_MESSAGE); 
                }
        } catch (SQLException ex) {
                   JOptionPane.showMessageDialog(rootPane, "Não Tem Permissão Para Acessar Essa Funcionalidade, Contacte O Administrador!","ERRO", JOptionPane.ERROR_MESSAGE); 
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCadastroMaterialActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
           try {
            conex.executaSql("select * from usuario where nome='"+jLabelUsuario.getText()+"'");
            conex.rs.first();
                if(conex.rs.getString("tipo").equals("Administrador")){
                   if(info==null){
                       info = new Info();
                       info.setVisible(true);
                       info.setResizable(false);
                   }else{
                       info.setVisible(true);
                       info.setResizable(false);                         
                   }
                }else{
                   JOptionPane.showMessageDialog(rootPane, "Não Tem Permissão Para Acessar Essa Funcionalidade, Contacte O Administrador!","ERRO", JOptionPane.ERROR_MESSAGE); 
                }
        } catch (SQLException ex) {
                   JOptionPane.showMessageDialog(rootPane, "Não Tem Permissão Para Acessar Essa Funcionalidade, Contacte O Administrador!","ERRO", JOptionPane.ERROR_MESSAGE); 
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        try {
            conex.executaSql("select * from usuario where nome='"+jLabelUsuario.getText()+"'");
            conex.rs.first();
                if(conex.rs.getString("tipo").equals("Administrador")){
                   if(fornecedor==null){
                       fornecedor = new CadastroDeFornecedor();
                       fornecedor.setVisible(true);
                       fornecedor.setResizable(false); 
                   }else{
                       fornecedor.setVisible(true);
                       fornecedor.setResizable(false);                         
                   }
                    //CadastroDeFornecedores f = new CadastroDeFornecedor();
                    //f.setVisible(true);
                    //f.setResizable(false);   
                }else{
                   JOptionPane.showMessageDialog(rootPane, "Não Tem Permissão Para Acessar Essa Funcionalidade, Contacte O Administrador!","ERRO", JOptionPane.ERROR_MESSAGE); 
                }
        } catch (SQLException ex) {
                   JOptionPane.showMessageDialog(rootPane, "Não Tem Permissão Para Acessar Essa Funcionalidade, Contacte O Administrador!","ERRO", JOptionPane.ERROR_MESSAGE); 
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        try {
            conex.executaSql("select * from usuario where nome='"+jLabelUsuario.getText()+"'");
            conex.rs.first();
                if(conex.rs.getString("tipo").equals("Administrador")){
                   if(usuario==null){
                       usuario = new CadastroDeUsuarios();
                       usuario.setVisible(true);
                       usuario.setResizable(false); 
                   }else{
                       usuario.setVisible(true);
                       usuario.setResizable(false);                         
                   }
                }else{
                   JOptionPane.showMessageDialog(rootPane, "Não Tem Permissão Para Acessar Essa Funcionalidade, Contacte O Administrador!","ERRO", JOptionPane.ERROR_MESSAGE); 
                }
        } catch (SQLException ex) {
                   JOptionPane.showMessageDialog(rootPane, "Não Tem Permissão Para Acessar Essa Funcionalidade, Contacte O Administrador!","ERRO", JOptionPane.ERROR_MESSAGE); 
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        try {
            conex.executaSql("select * from usuario where nome='"+jLabelUsuario.getText()+"'");
            conex.rs.first();
                if(conex.rs.getString("tipo").equals("Administrador")){
                   if(funcionario==null){
                       funcionario = new CadastroDeFuncionarios();
                       funcionario.setVisible(true);
                       funcionario.setResizable(false); 
                   }else{
                       funcionario.setVisible(true);
                       funcionario.setResizable(false);                         
                   }
                   //CadastroDeUsuarios c1 = new CadastroDeUsuarios();
                   //c1.setVisible(true);
                   //c1.setResizable(false);   
                }else{
                   JOptionPane.showMessageDialog(rootPane, "Não Tem Permissão Para Acessar Essa Funcionalidade, Contacte O Administrador!","ERRO", JOptionPane.ERROR_MESSAGE); 
                }
        } catch (SQLException ex) {
                   JOptionPane.showMessageDialog(rootPane, "Não Tem Permissão Para Acessar Essa Funcionalidade, Contacte O Administrador!","ERRO", JOptionPane.ERROR_MESSAGE); 
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
                   if(cliente==null){
                       cliente = new CadastroDeClientes();
                       cliente.setVisible(true);
                       cliente.setResizable(false); 
                   }else{
                       cliente.setVisible(true);
                       cliente.setResizable(false);                         
                   }
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        try {
            conex.executaSql("select * from usuario where nome='"+jLabelUsuario.getText()+"'");
            conex.rs.first();
                if(conex.rs.getString("tipo").equals("Administrador")){
                    if(material==null){
                       material = new CadastroDeMaterial();
                       material.setVisible(true);
                       material.setResizable(false); 
                   }else{
                       material.setVisible(true);
                       material.setResizable(false);                         
                   }
                    //CadastroDeMaterial c1 = new CadastroDeMaterial();
                    //c1.setVisible(true);
                    //c1.setResizable(false);   
                }else{
                   JOptionPane.showMessageDialog(rootPane, "Não Tem Permissão Para Acessar Essa Funcionalidade, Contacte O Administrador!","ERRO", JOptionPane.ERROR_MESSAGE); 
                }
        } catch (SQLException ex) {
                   JOptionPane.showMessageDialog(rootPane, "Não Tem Permissão Para Acessar Essa Funcionalidade, Contacte O Administrador!","ERRO", JOptionPane.ERROR_MESSAGE); 
        }         // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        try {
            conex.executaSql("select * from usuario where nome='"+jLabelUsuario.getText()+"'");
            conex.rs.first();
                if(conex.rs.getString("tipo").equals("Administrador")){
                    if(material==null){
                       stock = new StockMaterial();
                       stock.setVisible(true);
                       stock.setResizable(false); 
                   }else{
                       stock.setVisible(true);
                       stock.setResizable(false);                         
                   }                    
                    //StockMaterial s = new StockMaterial();
                    //s.setVisible(true);
                    //s.setResizable(false);   
                }else{
                   JOptionPane.showMessageDialog(rootPane, "Não Tem Permissão Para Acessar Essa Funcionalidade, Contacte O Administrador!","ERRO", JOptionPane.ERROR_MESSAGE); 
                }
        } catch (SQLException ex) {
                   JOptionPane.showMessageDialog(rootPane, "Não Tem Permissão Para Acessar Essa Funcionalidade, Contacte O Administrador!","ERRO", JOptionPane.ERROR_MESSAGE); 
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        try {
            conex.executaSql("select * from usuario where nome='"+jLabelUsuario.getText()+"'");
            conex.rs.first();
                if(conex.rs.getString("tipo").equals("Administrador")){
                    //Agendamento a = new Agendamento();
                   //a.setVisible(true);
                   //a.setResizable(false);   
                }else{
                   JOptionPane.showMessageDialog(rootPane, "Não Tem Permissão Para Acessar Essa Funcionalidade, Contacte O Administrador!","ERRO", JOptionPane.ERROR_MESSAGE); 
                }
        } catch (SQLException ex) {
                   JOptionPane.showMessageDialog(rootPane, "Não Tem Permissão Para Acessar Essa Funcionalidade, Contacte O Administrador!","ERRO", JOptionPane.ERROR_MESSAGE); 
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
     if(entrega==null){
        entrega= new ProntaEntrega();
        entrega.setVisible(true);
        entrega.setResizable(false);
     }else{
        entrega.setVisible(true);
        entrega.setResizable(false);
     }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        try {
            conex.executaSql("select * from usuario where nome='"+jLabelUsuario.getText()+"'");
            conex.rs.first();
                if(conex.rs.getString("tipo").equals("Administrador")){
                 if(financa==null){
                 financa= new Financas();
                 financa.setVisible(true);
                 financa.setResizable(false);
                }else{
                   financa.setVisible(true);
                   financa.setResizable(false);
                }   
                }else{
                   JOptionPane.showMessageDialog(rootPane, "Não Tem Permissão Para Acessar Essa Funcionalidade, Contacte O Administrador!","ERRO", JOptionPane.ERROR_MESSAGE); 
                }
        } catch (SQLException ex) {
                   JOptionPane.showMessageDialog(rootPane, "Não Tem Permissão Para Acessar Essa Funcionalidade, Contacte O Administrador!","ERRO", JOptionPane.ERROR_MESSAGE); 
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void timer1OnTime(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timer1OnTime
        //Agora A Hora Do Sistema    
        Hora mostra_hora = new Hora();
        mostra_hora.ler_hora();
        jLabelHoraDoSistema.setText("Hora " +mostra_hora.hora);        // TODO add your handling code here:
    }//GEN-LAST:event_timer1OnTime

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonAdicionar;
    private javax.swing.JButton jButtonAgendamento;
    private javax.swing.JButton jButtonCadastroClientes;
    private javax.swing.JButton jButtonCadastroFuncionarios;
    private javax.swing.JButton jButtonCadastroMaterial;
    private javax.swing.JButton jButtonCadastroUsuarios;
    private javax.swing.JButton jButtonFornecedores;
    private javax.swing.JButton jButtonVenda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelDataDoSistema;
    private javax.swing.JLabel jLabelHoraDoSistema;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuDeInformacaoDoSistema;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private org.netbeans.examples.lib.timerbean.Timer timer1;
    // End of variables declaration//GEN-END:variables
}
